import type { TeamMember } from "./team";

export interface YearTeam {
  year: number;
  members: TeamMember[];
}

export const previousTeams: YearTeam[] = [
  {
    year: 2023,
    members: [
      {
        name: "Rahul Sharma",
        role: "Team Captain",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2023/rahul.jpg",
        link: null,
      },
      {
        name: "Priya Patel",
        role: "Technical Lead",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2023/priya.jpg",
        link: null,
      },
      {
        name: "Arjun Kumar",
        role: "Optical Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2023/arjun.jpg",
        link: null,
      },
      {
        name: "Neha Singh",
        role: "Radio Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2023/neha.jpg",
        link: null,
      },
      {
        name: "Vikram Reddy",
        role: "DDA Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2023/vikram.jpg",
        link: null,
      },
      {
        name: "Ananya Desai",
        role: "Research Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2023/ananya.jpg",
        link: null,
      },
      {
        name: "Karthik Menon",
        role: "Event Management Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2023/karthik.jpg",
        link: null,
      },
      {
        name: "Divya Krishnan",
        role: "PR Lead",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2023/divya.jpg",
        link: null,
      },
    ],
  },
  {
    year: 2022,
    members: [
      {
        name: "Aditya Verma",
        role: "Team Captain",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2022/aditya.jpg",
        link: null,
      },
      {
        name: "Sneha Gupta",
        role: "Technical Lead",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2022/sneha.jpg",
        link: null,
      },
      {
        name: "Rohan Mehta",
        role: "Optical Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2022/rohan.jpg",
        link: null,
      },
      {
        name: "Tanvi Joshi",
        role: "Radio Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2022/tanvi.jpg",
        link: null,
      },
      {
        name: "Varun Nair",
        role: "DDA Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2022/varun.jpg",
        link: null,
      },
      {
        name: "Ishita Sharma",
        role: "Research Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2022/ishita.jpg",
        link: null,
      },
      {
        name: "Amit Kumar",
        role: "Event Management Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2022/amit.jpg",
        link: null,
      },
      {
        name: "Pooja Reddy",
        role: "PR Lead",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2022/pooja.jpg",
        link: null,
      },
    ],
  },
  {
    year: 2021,
    members: [
      {
        name: "Nikhil Sharma",
        role: "Team Captain",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2021/nikhil.jpg",
        link: null,
      },
      {
        name: "Anjali Patel",
        role: "Technical Lead",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2021/anjali.jpg",
        link: null,
      },
      {
        name: "Vishal Kumar",
        role: "Optical Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2021/vishal.jpg",
        link: null,
      },
      {
        name: "Meera Singh",
        role: "Radio Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2021/meera.jpg",
        link: null,
      },
      {
        name: "Rajesh Nair",
        role: "DDA Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2021/rajesh.jpg",
        link: null,
      },
      {
        name: "Kavya Desai",
        role: "Research Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2021/kavya.jpg",
        link: null,
      },
      {
        name: "Suresh Menon",
        role: "Event Management Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2021/suresh.jpg",
        link: null,
      },
      {
        name: "Riya Krishnan",
        role: "PR Lead",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2021/riya.jpg",
        link: null,
      },
    ],
  },
  {
    year: 2020,
    members: [
      {
        name: "Aarav Verma",
        role: "Team Captain",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2020/aarav.jpg",
        link: null,
      },
      {
        name: "Zara Gupta",
        role: "Technical Lead",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2020/zara.jpg",
        link: null,
      },
      {
        name: "Dhruv Mehta",
        role: "Optical Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2020/dhruv.jpg",
        link: null,
      },
      {
        name: "Ananya Joshi",
        role: "Radio Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2020/ananya.jpg",
        link: null,
      },
      {
        name: "Karan Nair",
        role: "DDA Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2020/karan.jpg",
        link: null,
      },
      {
        name: "Shreya Sharma",
        role: "Research Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2020/shreya.jpg",
        link: null,
      },
      {
        name: "Rohan Kumar",
        role: "Event Management Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2020/rohan.jpg",
        link: null,
      },
      {
        name: "Priya Reddy",
        role: "PR Lead",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2020/priya.jpg",
        link: null,
      },
    ],
  },
  {
    year: 2019,
    members: [
      {
        name: "Vihaan Sharma",
        role: "Team Captain",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2019/vihaan.jpg",
        link: null,
      },
      {
        name: "Ishani Patel",
        role: "Technical Lead",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2019/ishani.jpg",
        link: null,
      },
      {
        name: "Arnav Kumar",
        role: "Optical Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2019/arnav.jpg",
        link: null,
      },
      {
        name: "Tanvi Singh",
        role: "Radio Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2019/tanvi.jpg",
        link: null,
      },
      {
        name: "Ved Nair",
        role: "DDA Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2019/ved.jpg",
        link: null,
      },
      {
        name: "Anika Desai",
        role: "Research Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2019/anika.jpg",
        link: null,
      },
      {
        name: "Krish Menon",
        role: "Event Management Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2019/krish.jpg",
        link: null,
      },
      {
        name: "Nandini Krishnan",
        role: "PR Lead",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2019/nandini.jpg",
        link: null,
      },
    ],
  },
  {
    year: 2018,
    members: [
      {
        name: "Reyansh Verma",
        role: "Team Captain",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2018/reyansh.jpg",
        link: null,
      },
      {
        name: "Kiara Gupta",
        role: "Technical Lead",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2018/kiara.jpg",
        link: null,
      },
      {
        name: "Vihaan Mehta",
        role: "Optical Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2018/vihaan.jpg",
        link: null,
      },
      {
        name: "Anvi Joshi",
        role: "Radio Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2018/anvi.jpg",
        link: null,
      },
      {
        name: "Vedant Nair",
        role: "DDA Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2018/vedant.jpg",
        link: null,
      },
      {
        name: "Shanaya Sharma",
        role: "Research Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2018/shanaya.jpg",
        link: null,
      },
      {
        name: "Rudra Kumar",
        role: "Event Management Head",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2018/rudra.jpg",
        link: null,
      },
      {
        name: "Pariya Reddy",
        role: "PR Lead",
        linkedin: null,
        instagram: null,
        image: "/team/previous/2018/pariya.jpg",
        link: null,
      },
    ],
  },
]; 